cache:
  - '%LOCALAPPDATA%\pip\Cache'
environment:
  global:
    PYTEST_ADDOPTS: "-m 'not (edge or safari or phantomjs)'"
  matrix:
    - TOXENV: flake8
      PYTHON_HOME: C:\Python36
    - TOXENV: docs
      PYTHON_HOME: C:\Python36
    - TOXENV: py27
      PYTHON_HOME: C:\Python27
    - TOXENV: py36
      PYTHON_HOME: C:\Python36
install:
  # - choco install firefox
  # - choco install googlechrome
  # - choco install selenium-chrome-driver
  # - choco install selenium-ie-driver
  # - choco install selenium-gecko-driver
  - 'set PATH=C:\tools\selenium;%PATH%'
  - '%PYTHON_HOME%\Scripts\pip --version'
  - '%PYTHON_HOME%\Scripts\pip install tox'
build: off
before_test:
  - chromedriver.exe --version
  - geckodriver.exe --version
  - IEDriverServer.exe --version
test_script:
  - cmd: '%PYTHON_HOME%\Scripts\tox'
